### ISSUE TITLE
Hide program to tray

### ISSUE THREAD

**Issue by vyakovlev** [TizianGth/Wireless-Button-Reprogrammer#1]
**Is your feature request related to a problem? Please describe.**
When I run your amazing tool it stays in my taskbar and this is confusing, when I need to change apps with alt-tab or have a quick view on running apps (what is this console app in my taskbar?).

**Describe the solution you'd like**
It would be great to add a button `Hide` to put an icon to Windows tray / system notifications area or even `Install` to automatically put the app in the tray and run on Windows boot.

**Describe alternatives you've considered**
It's also fine to have a `Hide` button, that just hides the app from everywhere and you have to start it again to make changes

**Comment by TizianGth** [comment]
I apologize for responding to you this late, but ofc I'll have a look what I can do. Thank you for your engagement , I hope my programm works fine otherwise.

**Comment by TizianGth** [comment]
Hey, have a look at the latest release and let me know if that solved your problems :)

**Comment by TizianGth** [comment]
Hi, have a look at the newest release. Let me know if that solved your problems :)

**Comment by vyakovlev** [comment]
Hi Tizian, I've had only 15 mins to test tonight, but new release seems to do the job right! Thank you!

I saw you need an icon for the app, I'll try to create something for you (us) 😄

**Comment by vyakovlev** [comment]
I'm not a UI/UX person, just tried to design something what I feel like WBR, here it is

![WBR_logo](https://github.com/user-attachments/assets/ee4461fb-a25b-4a24-8581-dacbc8fe6915)

Hope you could make an icon from it. If you need other colors, here's the base

![WBR_blank](https://github.com/user-attachments/assets/16c6bac7-4353-40e5-a1ef-55bd0f6991db)

**Comment by TizianGth** [comment]
I'm no designer either but thank you! I'm really happy that it's not thie ugly white circle anymore. You can already see the change in the latest 1.2.0 release. Altough I like purple very much (it's my favourite color) and it fits really well with the logo, I felt like it didn't fit with the overall 'desaturated blue' color scheme, so I changed that. I hope your not that mad that haha

**Comment by TizianGth** [comment]
I'll close this issue now, if you have any other problems/proposals feel free to open another one :)

**Comment by vyakovlev** [comment]
> I'm no designer either but thank you! I'm really happy that it's not thie ugly white circle anymore. You can already see the change in the latest 1.2.0 release. Altough I like purple very much (it's my favourite color) and it fits really well with the logo, I felt like it didn't fit with the overall 'desaturated blue' color scheme, so I changed that. I hope your not that mad that haha

Looks great! Thank you

**Comment by vyakovlev** [comment]
> I'll close this issue now, if you have any other problems/proposals feel free to open another one :)

Sure. Thanks again!
