### ISSUE TITLE
HyperX Cloud Wireless III

### ISSUE THREAD

**Issue by bakiras001** [TizianGth/Wireless-Button-Reprogrammer#4]
Hi, 

Can you please make this prgram for HyperX Cloud Wireless III ?

Thanks in advance

**Comment by TizianGth** [comment]
Hi, have a look [here](https://github.com/TizianGth/Wireless-Button-Reprogrammer/releases/tag/Debug). Just follow the instructions and send me the result. There seems to be a problem with the debug.exe rn for some users, so lmk if something doesn't work

**Comment by bakiras001** [comment]
debug.exe is not working for me

![Capture](https://github.com/user-attachments/assets/f16690a2-9639-45eb-ba29-7a492e4e41ee)

**Comment by TizianGth** [comment]
That's so weird. It works for me and it definitely worked for other people in the past. Unfortunately I don't have much time at the moment, it will take a while until I can take a closer look at what the problem is

**Comment by bakiras001** [comment]
I'm new to this, so I might be doing something wrong. Should I copy the debug files to the WBR folder?
Also, where should I input the VID and PID? Is it supposed to go into one of the debug files?

**Comment by bakiras001** [comment]
I'm new to this, so I might be doing something wrong. Should I copy the debug files to the WBR folder?

**Comment by TizianGth** [comment]
No worries. If it doesn't say otherwise, there's no need to copy the files. I updated the [Debug.zip](https://github.com/TizianGth/Wireless-Button-Reprogrammer/releases/tag/Debug), just unzip it execute the .exe and follow the instructions given. Lmk if it works now :)

**Comment by DJWalia** [comment]
Hi! I'm also using the Cloud III and was able to run debug.exe, I got 3 devices detected all with the same VID/PID. This was my output:

Id: 1, Vid: 03f0, Pid: 0c9d (Hexadecimal)
Id: 2, Vid: 03f0, Pid: 0c9d (Hexadecimal)
Id: 3, Vid: 03f0, Pid: 0c9d (Hexadecimal)

Not sure where to go from here.

**Comment by bakiras001** [comment]
Here is the Debug result
![Capture](https://github.com/user-attachments/assets/86517ba8-b9b8-4de1-80d3-32a4b28c046b)
[debug.json](https://github.com/user-attachments/files/18247335/debug.json)

**Comment by TizianGth** [comment]
@bakiras001 Thank you, have a look [here](https://github.com/Tiziam/Wireless-Button-Reprogrammer/releases/tag/Test). Input the Vendor and Product ID, select HyperX Cloud Wireless III from the devices selection, press apply and lmk if it works.

**Comment by TizianGth** [comment]
@DJWalia You can try the test version too as you've already got your VID and PID. Tbh idk why the other steps didn't work/weren't displayed

**Comment by bakiras001** [comment]
Thanks man. It is working. 
Merry Xmas and advance Happy New Year

**Comment by Tiziam** [comment]
I'm sorry I don't understand what exactly happens, could you explain further? Also could you send me the errors.txt? (you can find it in the %appdata% folder)

**Comment by TizianGth** [comment]
I'm glad it worked, merry christmas and happy new year to you too!

@DJWalia I'll close this issue, have a look at the latest [release](https://github.com/Tiziam/Wireless-Button-Reprogrammer/releases). If it doesn't work please open a new issue.

**Comment by bakiras001** [comment]
There is an issue. Program closes after every single activation

**Comment by TizianGth** [comment]
That's not good. Can you send me the errors.txt (%appdata% -> WBR)

**Comment by bakiras001** [comment]
The error file didn't create sometimes. I placed WBR in both x64 folder and x86 folder.
Now WBR in x64 folder. and here is the error file
[errors.txt](https://github.com/user-attachments/files/18247533/errors.txt)

**Comment by TizianGth** [comment]
Okay thx, the folder shouldn't matter though. Download this and send me the errors.txt
https://github.com/Tiziam/Wireless-Button-Reprogrammer/releases/tag/Test

**Comment by bakiras001** [comment]
[errors.txt](https://github.com/user-attachments/files/18247561/errors.txt)

**Comment by bakiras001** [comment]
> Okay thx, the folder shouldn't matter though. Download this and send me the errors.txt https://github.com/Tiziam/Wireless-Button-Reprogrammer/releases/tag/Test

Now the program is not closing

**Comment by bakiras001** [comment]
But showing two icons in system tray

![Capture1](https://github.com/user-attachments/assets/43b5b0a3-7a2b-42ac-9f64-0b24b65e4fcf)

**Comment by TizianGth** [comment]
It works now?
I updated it now in the proper release, It'd be nice if you confirmed that this version also works.
https://github.com/Tiziam/Wireless-Button-Reprogrammer/releases/tag/1.2.5

**Comment by bakiras001** [comment]
> It works now? I updated it now in the proper release, It'd be nice if you confirmed that this version also works. https://github.com/Tiziam/Wireless-Button-Reprogrammer/releases/tag/1.2.5

Let me check

**Comment by TizianGth** [comment]
> But showing two icons in system tray
> 
> ![Capture1](https://private-user-images.githubusercontent.com/190124048/398606326-43b5b0a3-7a2b-42ac-9f64-0b24b65e4fcf.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxNzMwNTEsIm5iZiI6MTczNTE3Mjc1MSwicGF0aCI6Ii8xOTAxMjQwNDgvMzk4NjA2MzI2LTQzYjViMGEzLTdhMmItNDJhYy05ZjY0LTBiMjRiNjVlNGZjZi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNlQwMDI1NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYmIwZDE5ZWMzMWQ5NDUzMTQzNTBmMWRkMmY2NzMxYmIxNjE1NTQ4MTk5NzNkN2U2NWIxYjlkMDA1OWZkMDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z9XazVDelTg0xdEKU7RR9xVQAP6HcJs_Q8J4r3jv6vA)

Yes, thank you for bringing that up, maybe check if there are 2 instances running by clicking the icons. But I've also noticed that this happens sometimes, although they seem to disapear once I hover over them. It's on my todo list

**Comment by bakiras001** [comment]
It didn't disappear when I hover. It's not a big deal though. Just pointing out.
Thank you so much Tiziam.

**Comment by TizianGth** [comment]
So I hope the currently uploaded version works?
I'd like to close this issue, It'd be better for my organisation if you quickly opened a issue for the icon bug. Thx for your patience though

**Comment by bakiras001** [comment]
Yes. It's working perfectly.
You can close the issue
